name: ACTION WORKFLOW

on: [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: LIST FILES BEFORE ANY CHANGE
        run: |
          hostname
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      # The following action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: CHECKOUT
        uses: actions/checkout@v2.3.1
        # The "CHECKOUT" step is the same as executing these commands:
        # git clone git@github:$GITHUB_REPOSITORY
        # git checkout $GITHUB_SHA

      - name: LIST FILES AFTER PREVIOUS STEP
        run: |
          hostname
          pwd
          ls -la
      - name: SIMPLE JAVASCRIPT ACTION
        id: greet
        # We are referencing an External Action from another GIT repository
        uses: actions/hello-world-javascript-action@v1
        # The referencing Action requires an input (who-to-greet), which is why "with" is been used
        with:
          who-to-greet: Obito
      - name: LOG CREATION TIME
        # the following echo is calling a variable by using "${{". 
          # steps = calls a steps in this action workflow
          # greet = the ID of the step been called (check line 10)
          # output = the external action calls will generate an output
          # time = output name according to the external action
          # external action wiki: https://github.com/actions/hello-world-javascript-action
        run: echo "${{ steps.greet.outputs.time }}"