name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
    steps:
      - name: LOG NODE VERSION
        run: |
          node -v
          cat /etc/os-release
          hostname
          whoami
      