name: Shell command

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: ECHO A STRING
        run: echo "Hello Github World"
      - name: MULTILINE SCRIPT
        # the "|" will tell gh actions to execute multiple commands
        run: |
          node -v
          npm -v
          hostname
      - name: PYTHON COMMANDS
        run: |
          import platform
          print (platform.processor())
        shell: python
  runs-windows-command:
    runs-on: windows-latest
    # the "needs" will create a dependency before executing the next job
    needs: [run-shell-command]
    steps:
      # the default shell in for GitHub runners is PowerShell
      - name: DIRECTORY POWERSHELL
        run: Get-Location
      - name: DIRECTORY BASH
        run: |
          pwd
          hostname
        shell: bash