name: Shell command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Github World"
      - name: multi-line script
        run: |
          node -v
          npm -v
          hostname
      - name: python Commands
        run: |
          import platform
          print (platform.processor())
      shell: python